name: On Push
on:
  push:
    branches:
      - master
      
jobs:
  build:
    name: Building cython code
    runs-on: ubuntu-latest
    steps:
    - name: Checking out code...
      id: checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: build_and_test
      id: build_and_test
      uses: ./.github/actions/build_and_test
      
